# pls completion                                           -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_pls_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"
  
  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_pls_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'sleep'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'calc'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'hlp'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'tty'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'off'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'out'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'ver'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'opn'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A directory -A file -- "$cur" )
      ;;

    'sh'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'wm'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'rb'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "")" -- "$cur" )
      ;;

    'rm'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A directory -A file -- "$cur" )
      ;;

    'mv'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A directory -A file -- "$cur" )
      ;;

    'cp'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A directory -A file -- "$cur" )
      ;;

    *)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_pls_completions_filter "hlp sh wm tty opn rm mv cp calc off rb sleep out ver")" -- "$cur" )
      ;;

  esac
} &&
complete -F _pls_completions pls

# ex: filetype=sh
